-- ========================================================
-- SCHEMA FILE: PosNBL Food Database
-- Generated from Supabase Data Backup
-- ========================================================

-- --------------------------------------------------------
-- 1. Create Tables Structure (สร้างโครงสร้างตาราง)
-- --------------------------------------------------------

-- ตารางหมวดหมู่อาหาร (food_groups)
CREATE TABLE IF NOT EXISTS public.food_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

-- ตารางรายการอาหาร (foods)
CREATE TABLE IF NOT EXISTS public.foods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint REFERENCES public.food_groups(id) ON DELETE SET NULL,
    name character varying NOT NULL,
    requires_stock boolean DEFAULT false,
    price_1 numeric DEFAULT 0,
    price_2 numeric DEFAULT 0,
    price_3 numeric DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);


-- --------------------------------------------------------
-- 2. Insert Data: food_groups (เพิ่มข้อมูลหมวดหมู่อาหาร)
-- --------------------------------------------------------

INSERT INTO public.food_groups (id, name) VALUES
(1, 'ข้าวกล่อง'),
(2, 'ต้ม / แกง'),
(3, 'ทอด / ยำ'),
(4, 'ข้าว / ข้าวต้ม'),
(5, 'ลาบ / ก้อย / ซอยจุ๊'),
(6, 'เมนูพิเศษ'),
(7, 'ส้มตำ'),
(8, 'ลูกค้าฝากซื้อ')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;


-- --------------------------------------------------------
-- 3. Insert Data: foods (เพิ่มข้อมูลรายการอาหาร)
-- --------------------------------------------------------

INSERT INTO public.foods (id, group_id, name, requires_stock, price_1, price_2, price_3) VALUES
(1, 4, 'ข้าวเหนียว', true, 10, 10, 10),
(2, 4, 'ข้าวสวย', true, 10, 10, 10),
(3, 7, 'ตำปูปลาร้า', true, 60, 60, 60),
(4, 7, 'ตำถั่ว', true, 60, 60, 60),
(5, 7, 'ตำไทย', true, 70, 70, 70),
(6, 7, 'ตำป่า', true, 70, 70, 70),
(7, 7, 'ตำแตง', true, 70, 70, 70),
(8, 7, 'ตำหอยดอง', true, 70, 70, 70),
(9, 7, 'ตำไทยไข่เค็ม', true, 80, 80, 80),
(10, 7, 'ตำกุ้งสด', true, 100, 100, 100),
(11, 7, 'ตำทะเลรวม', true, 100, 100, 100),
(12, 2, 'แซ่บกระดูกอ่อน', true, 80, 120, 100),
(13, 2, 'แซ่บเนื้อ', true, 80, 120, 100),
(14, 2, 'ต้มขม', true, 80, 120, 100),
(15, 2, 'แกงอ่อมหมู', true, 80, 120, 100),
(16, 2, 'แกงอ่อมเนื้อ', true, 80, 120, 100),
(17, 2, 'ต้มยำรวมมิตร', true, 80, 120, 100),
(18, 3, 'ยำรวมมิตร (วุ้นเส้น)', true, 80, 120, 100),
(19, 3, 'ยำรวมมิตร (มาม่า)', true, 80, 120, 100),
(20, 5, 'ลาบหมู', true, 80, 120, 100),
(21, 5, 'ก้อยหมู', true, 80, 120, 100),
(22, 5, 'ลาบเนื้อ', true, 80, 120, 100),
(23, 5, 'ก้อยเนื้อ', true, 80, 120, 100),
(24, 5, 'น้ำตกหมู', true, 80, 120, 100),
(25, 5, 'ตับหวาน', true, 80, 120, 100),
(26, 5, 'ลวกจิ้ม', true, 80, 120, 100),
(27, 3, 'หมูทอด', true, 80, 120, 100),
(28, 3, 'เนื้อทอด', true, 80, 120, 100),
(29, 3, 'คอหมูย่าง', true, 80, 120, 100),
(30, 5, 'ซอยจุ๊', true, 160, 200, 180),
(31, 1, 'ข้าวผัดไข่', true, 50, 50, 50),
(32, 1, 'ข้าวผัดหมู', true, 50, 50, 50),
(33, 1, 'ข้าวไข่เจียว', true, 50, 50, 50),
(34, 1, 'กระเพราหมู', true, 50, 50, 50),
(35, 1, 'กระเพราไก่', true, 50, 50, 50),
(36, 1, 'หมูกระเทียม', true, 50, 50, 50),
(37, 1, 'ข้าวผัดทะเล', true, 60, 60, 60),
(38, 1, 'กระเพราทะเล', true, 60, 60, 60),
(39, 1, 'กระเพราเนื้อ', true, 60, 60, 60),
(40, 1, 'ข้าวผัดแหนม', true, 60, 60, 60),
(41, 1, 'กระเพราแหนม', true, 60, 60, 60),
(42, 1, 'กระเพราหมูกรอบ', true, 60, 60, 60),
(43, 1, 'คะน้าหมูกรอบ', true, 60, 60, 60),
(44, 1, 'ไก่ย่าง', true, 250, 250, 250)
ON CONFLICT (id) DO UPDATE SET 
    group_id = EXCLUDED.group_id,
    name = EXCLUDED.name,
    requires_stock = EXCLUDED.requires_stock,
    price_1 = EXCLUDED.price_1,
    price_2 = EXCLUDED.price_2,
    price_3 = EXCLUDED.price_3;

-- ปรับ Sequence ID ให้รันต่อจาก ID ล่าสุดโดยอัตโนมัติ
SELECT setval('food_groups_id_seq', (SELECT MAX(id) FROM public.food_groups));
SELECT setval('foods_id_seq', (SELECT MAX(id) FROM public.foods));
