-- 1. customer_groups
CREATE TABLE IF NOT EXISTS public.customer_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. food_groups
CREATE TABLE IF NOT EXISTS public.food_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT
);

-- 3. food_mappings
CREATE TABLE IF NOT EXISTS public.food_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id BIGINT,
    stock_id BIGINT,
    stock_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. food_stocks
CREATE TABLE IF NOT EXISTS public.food_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_name TEXT,
    quantity NUMERIC DEFAULT 0,
    unit TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. foods
CREATE TABLE IF NOT EXISTS public.foods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    requires_stock BOOLEAN DEFAULT FALSE,
    group_id BIGINT,
    price_1 NUMERIC DEFAULT 0,
    price_2 NUMERIC DEFAULT 0,
    price_3 NUMERIC DEFAULT 0
);

-- 6. locations
CREATE TABLE IF NOT EXISTS public.locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. zones
CREATE TABLE IF NOT EXISTS public.zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    location_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. orders
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    customer_group TEXT,
    total_price NUMERIC DEFAULT 0,
    total_qty INT DEFAULT 0,
    items JSONB,
    phone TEXT,
    location_name TEXT,
    zone_name TEXT,
    order_date TIMESTAMPTZ,
    status TEXT DEFAULT 'pending',
    customer_group_id BIGINT,
    note TEXT,
    customer_phone TEXT,
    location_id BIGINT,
    zone_id BIGINT,
    delivery_fee NUMERIC DEFAULT 0,
    subtotal NUMERIC DEFAULT 0
);
